### ISSUE TITLE
еще раз об адаптере

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn-er-bridge#12]
Адаптер это просто информация о связи модели с конкретной структурой реляционной бд. Мы ни в коем случае не должны делать никаких выводов и не придпринимать никаких действий по информации из адаптера. Он ВТОРИЧЕН! А что имеем в коде для деревьев? Мы по данным из адаптера (rbField, lbField) начинаем думать: у нас тут интервальное дерево или нет. Это бред. Я убираю код. 

Правильно:

* На уровне Entity мы должны знать у нас плоская таблица, простое дерево или интервальное дерево. Адаптеры здесь ни при чем. Это должно следовать из типа Entity. Мы выбрали путь, что тип определяется полями. Т.е. есть три поля PARENT, LB, RB -- значит перед нами ИНТЕРВАЛЬНОЕ ДЕРЕВО. Есть только PARENT -- перед нами простое дерево. Нет этих полей -- перед нами просто таблица.

Всё! И никаких адаптеров тут не надо. Так как у нас смысл заложен в ИМЕНА ПОЛЕЙ. Они НЕ МОГУТ БЫТЬ другими.

**Comment by sywka** [comment]
Давайте тогда ещё раз проясним, мы делаем инструмент который будет работать только с гедымином или лучше, ведь эти достаточно жёсткие рамки по нэймингу будут ограничивать пользователя в выборе имени для атрибутов.

И ещё раз, адаптер и хранит только информацию о связях полей и их именах, больше ничего. Но в тоже время естественно при генерации физической структуры бд по логической в виде entity смотреть на эти связи и имена, и с учётом их строить бд

**Comment by gsbelarus** [comment]
1. Какой бы мы инструмент не делали, адаптер не несет никакой информации о структуре сущности. На него нельзя смотреть. Это просто информация какому-то промежуточному слою, в нашем случае gdmn-er-bridge, о том где в реляционной базе взять данные.
2. В будущем появятся и клиенты работающие только на GDMN2 и ничего не знающиео Гедымине в принципе, но в начале, и для существующих клиентов у нас будет одновременная работа и важно сохранить совместимость GDMN2-Гедемин по фундаментальным вещам.
3. Нет никакой трагедии в том, что некоторые имена полей будут зарезервированы на уровне платформы. PARENT, LB, RB... В будущем можно будет сделать их переменными, но сейчас зачем усложнять на ровном месте? Эти имена несут строго определенный смысл.
4. И еще раз повторюсь:

> На уровне Entity мы должны знать у нас плоская таблица, простое дерево или интервальное дерево. Адаптеры здесь ни при чем. Это должно следовать из типа Entity. Мы выбрали путь, что тип определяется полями. Т.е. есть три поля PARENT, LB, RB -- значит перед нами ИНТЕРВАЛЬНОЕ ДЕРЕВО. Есть только PARENT -- перед нами простое дерево. Нет этих полей -- перед нами просто 
таблица.

Для этого предумотрены свойства isTree, isLBRBTree на уровне Entity.
